//! Core A2A protocol domain types.
//!
//! Contains the fundamental types for task management, messaging, and content
//! representation in the A2A protocol.

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

// -- Enums --

/// Defines the possible lifecycle states of a `Task`.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum TaskState {
    /// The task is in an unknown or indeterminate state.
    #[default]
    TaskStateUnspecified,
    /// A task has been successfully submitted and acknowledged.
    TaskStateSubmitted,
    /// A task is actively being processed by the agent.
    TaskStateWorking,
    /// A task has finished successfully. Terminal state.
    TaskStateCompleted,
    /// A task has finished with an error. Terminal state.
    TaskStateFailed,
    /// A task was canceled before completion. Terminal state.
    TaskStateCanceled,
    /// The agent requires additional user input to proceed. Interrupted state.
    TaskStateInputRequired,
    /// The agent has decided not to perform the task. Terminal state.
    TaskStateRejected,
    /// Authentication is required to proceed. Interrupted state.
    TaskStateAuthRequired,
}

impl TaskState {
    /// Returns `true` if this is a terminal state (completed, failed, canceled,
    /// rejected).
    pub fn is_terminal(&self) -> bool {
        matches!(
            self,
            TaskState::TaskStateCompleted
                | TaskState::TaskStateFailed
                | TaskState::TaskStateCanceled
                | TaskState::TaskStateRejected
        )
    }

    /// Returns `true` if this is an interrupted state (input_required,
    /// auth_required).
    pub fn is_interrupted(&self) -> bool {
        matches!(
            self,
            TaskState::TaskStateInputRequired | TaskState::TaskStateAuthRequired
        )
    }
}

/// Defines the sender of a message in A2A protocol communication.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Role {
    /// The role is unspecified.
    #[default]
    RoleUnspecified,
    /// The message is from the client to the server.
    RoleUser,
    /// The message is from the server to the client.
    RoleAgent,
}

// -- Core Domain Structs --

/// `Task` is the core unit of action for A2A. It has a current status and when
/// results are created they are stored in artifacts. Multi-turn interactions
/// are stored in history.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Task {
    /// Unique identifier (UUID) for the task, generated by the server.
    pub id: String,

    /// Unique identifier (UUID) for the contextual collection of interactions.
    pub context_id: String,

    /// The current status of the task.
    pub status: TaskStatus,

    /// Output artifacts for the task.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub artifacts: Vec<Artifact>,

    /// The history of interactions for this task.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub history: Vec<Message>,

    /// Custom metadata about the task.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<HashMap<String, serde_json::Value>>,
}

/// A container for the status of a task.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaskStatus {
    /// The current state of this task.
    pub state: TaskState,

    /// A message associated with the status.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<Message>,

    /// ISO 8601 timestamp when the status was recorded.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<DateTime<Utc>>,
}

/// `Message` is one unit of communication between client and server.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Message {
    /// Unique identifier (UUID) of the message, created by the message creator.
    pub message_id: String,

    /// The context id of the message.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context_id: Option<String>,

    /// The task id of the message.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub task_id: Option<String>,

    /// Identifies the sender of the message.
    pub role: Role,

    /// Content parts of the message.
    pub parts: Vec<Part>,

    /// Any metadata to provide along with the message.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<HashMap<String, serde_json::Value>>,

    /// The URIs of extensions present or contributing to this message.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub extensions: Vec<String>,

    /// A list of task IDs that this message references for additional context.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub reference_task_ids: Vec<String>,
}

/// `Part` represents a container for a section of communication content.
///
/// Parts can be purely textual, a file (image, video, etc.), or a structured
/// data blob (JSON).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Part {
    /// The string content of a text part.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,

    /// Raw byte content of a file, base64-encoded in JSON.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub raw: Option<String>,

    /// A URL pointing to the file's content.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,

    /// Arbitrary structured data as a JSON value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,

    /// Metadata associated with this part.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<HashMap<String, serde_json::Value>>,

    /// An optional filename for the file.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,

    /// The MIME type of the part content.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub media_type: Option<String>,
}

impl Part {
    /// Creates a new text part.
    pub fn text(content: impl Into<String>) -> Self {
        Self {
            text: Some(content.into()),
            raw: None,
            url: None,
            data: None,
            metadata: None,
            filename: None,
            media_type: Some("text/plain".to_string()),
        }
    }

    /// Creates a new data part with arbitrary JSON.
    pub fn data(value: serde_json::Value) -> Self {
        Self {
            text: None,
            raw: None,
            url: None,
            data: Some(value),
            metadata: None,
            filename: None,
            media_type: Some("application/json".to_string()),
        }
    }
}

/// Artifacts represent task outputs.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Artifact {
    /// Unique identifier (UUID) for the artifact, unique within a task.
    pub artifact_id: String,

    /// A human-readable name for the artifact.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// A human-readable description of the artifact.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// The content of the artifact. Must contain at least one part.
    pub parts: Vec<Part>,

    /// Metadata included with the artifact.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<HashMap<String, serde_json::Value>>,

    /// The URIs of extensions present or contributing to this artifact.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub extensions: Vec<String>,
}

// -- Streaming Events --

/// An event sent by the agent to notify the client of a change in a task's
/// status.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaskStatusUpdateEvent {
    /// The ID of the task that has changed.
    pub task_id: String,

    /// The ID of the context that the task belongs to.
    pub context_id: String,

    /// The new status of the task.
    pub status: TaskStatus,

    /// Metadata associated with the task update.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<HashMap<String, serde_json::Value>>,
}

/// A task delta where an artifact has been generated.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaskArtifactUpdateEvent {
    /// The ID of the task for this artifact.
    pub task_id: String,

    /// The ID of the context that this task belongs to.
    pub context_id: String,

    /// The artifact that was generated or updated.
    pub artifact: Artifact,

    /// If true, append content to a previously sent artifact with the same ID.
    #[serde(default)]
    pub append: bool,

    /// If true, this is the final chunk of the artifact.
    #[serde(default)]
    pub last_chunk: bool,

    /// Metadata associated with the artifact update.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<HashMap<String, serde_json::Value>>,
}

// -- Push Notifications --

/// Configuration for setting up push notifications for task updates.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PushNotificationConfig {
    /// A unique identifier (UUID) for this push notification configuration.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,

    /// The URL where the notification should be sent.
    pub url: String,

    /// A token unique for this task or session.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,

    /// Authentication information required to send the notification.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub authentication: Option<AuthenticationInfo>,
}

/// Defines authentication details, used for push notifications.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AuthenticationInfo {
    /// HTTP Authentication Scheme (e.g., "Bearer", "Basic", "Digest").
    pub scheme: String,

    /// Credentials. Format depends on the scheme.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub credentials: Option<String>,
}

/// A container associating a push notification configuration with a specific
/// task.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaskPushNotificationConfig {
    /// Tenant ID.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tenant: Option<String>,

    /// The ID of the task this configuration is associated with.
    pub task_id: String,

    /// The push notification configuration details.
    pub push_notification_config: PushNotificationConfig,
}

// -- Configuration --

/// Configuration of a send message request.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SendMessageConfiguration {
    /// Media types the client accepts for response parts.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub accepted_output_modes: Vec<String>,

    /// Push notification configuration for task updates.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub push_notification_config: Option<PushNotificationConfig>,

    /// Max number of recent messages to include in the response.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub history_length: Option<i32>,

    /// If true, wait until the task reaches a terminal or interrupted state.
    #[serde(default)]
    pub blocking: bool,
}

/// A list of strings (used in security requirements).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StringList {
    /// The individual string values.
    #[serde(default)]
    pub list: Vec<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_task_state_terminal() {
        assert!(TaskState::TaskStateCompleted.is_terminal());
        assert!(TaskState::TaskStateFailed.is_terminal());
        assert!(TaskState::TaskStateCanceled.is_terminal());
        assert!(TaskState::TaskStateRejected.is_terminal());
        assert!(!TaskState::TaskStateWorking.is_terminal());
        assert!(!TaskState::TaskStateInputRequired.is_terminal());
    }

    #[test]
    fn test_task_state_interrupted() {
        assert!(TaskState::TaskStateInputRequired.is_interrupted());
        assert!(TaskState::TaskStateAuthRequired.is_interrupted());
        assert!(!TaskState::TaskStateCompleted.is_interrupted());
    }

    #[test]
    fn test_task_state_serialization() {
        let state = TaskState::TaskStateWorking;
        let json = serde_json::to_string(&state).unwrap();
        assert_eq!(json, "\"TASK_STATE_WORKING\"");

        let deserialized: TaskState = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized, state);
    }

    #[test]
    fn test_role_serialization() {
        let role = Role::RoleAgent;
        let json = serde_json::to_string(&role).unwrap();
        assert_eq!(json, "\"ROLE_AGENT\"");
    }

    #[test]
    fn test_part_text_constructor() {
        let part = Part::text("hello world");
        assert_eq!(part.text.as_deref(), Some("hello world"));
        assert_eq!(part.media_type.as_deref(), Some("text/plain"));
        assert!(part.raw.is_none());
        assert!(part.url.is_none());
        assert!(part.data.is_none());
    }

    #[test]
    fn test_message_roundtrip() {
        let msg = Message {
            message_id: "msg-001".to_string(),
            context_id: Some("ctx-001".to_string()),
            task_id: None,
            role: Role::RoleUser,
            parts: vec![Part::text("Hello")],
            metadata: None,
            extensions: vec![],
            reference_task_ids: vec![],
        };

        let json = serde_json::to_string(&msg).unwrap();
        let deserialized: Message = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.message_id, "msg-001");
        assert_eq!(deserialized.role, Role::RoleUser);
        assert_eq!(deserialized.parts.len(), 1);
    }

    #[test]
    fn test_task_roundtrip() {
        let task = Task {
            id: "task-001".to_string(),
            context_id: "ctx-001".to_string(),
            status: TaskStatus {
                state: TaskState::TaskStateSubmitted,
                message: None,
                timestamp: None,
            },
            artifacts: vec![],
            history: vec![],
            metadata: None,
        };

        let json = serde_json::to_string_pretty(&task).unwrap();
        let deserialized: Task = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.id, "task-001");
        assert_eq!(deserialized.status.state, TaskState::TaskStateSubmitted);
    }
}
