version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    groups:
      opentelemetry:
        patterns:
          - "opentelemetry*"
      reqwest:
        patterns:
          - "reqwest*"

  - package-ecosystem: pub
    directory: /app
    schedule:
      interval: daily
    groups:
      all-pub:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: daily
    groups:
      all-docker:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      all-actions:
        patterns:
          - "*"
