-- Add title_locked flag to conversations.
--
-- The flag prevents the title-generator worker from overwriting a title that
-- has been set explicitly (manual rename or explicit title at creation) or
-- previously generated by the worker itself.
--
-- All existing rows with a non-NULL title are treated as already-titled and
-- locked so the worker never retroactively retitles them. Rows with NULL
-- titles remain unlocked.

ALTER TABLE conversations
    ADD COLUMN title_locked INTEGER NOT NULL DEFAULT 0;

UPDATE conversations
    SET title_locked = 1
    WHERE title IS NOT NULL;
