#!/bin/sh
set -e

# Reload the *system* systemd daemon so it picks up the new user-unit files
# in /usr/lib/systemd/user/ (this is safe to run as root).
if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload 2>/dev/null || true
fi

# On upgrade: re-enable and restart services that were previously enabled.
# On fresh install: just print instructions.
action="${1:-configure}"

# Migrate a single user from the legacy per-interface units to the new
# unified `assistant-orchestrator.service`. Idempotent: safe to re-run.
migrate_user_to_orchestrator() {
    user_id="$1"
    sysctl="systemctl --user -M ${user_id}@.host"

    # Resolve home early — also needed for the symlink-fallback detection below.
    user_home=$(getent passwd "$user_id" | cut -d: -f6)

    # Detect which legacy units were enabled. Two probes, in order:
    #   1. `is-enabled` — works while the unit file is still present.
    #   2. Symlink presence under ~/.config/systemd/user/default.target.wants/
    #      — required when dpkg has already removed the legacy unit files
    #      from /usr/lib/systemd/user/ before postinstall runs (the common
    #      upgrade path). `is-enabled` then returns "not-found" instead of
    #      "enabled", so we fall back to inspecting the wants/ directory
    #      directly. The dangling symlinks are also cleaned up below.
    interfaces=""
    wants_dir=""
    if [ -n "$user_home" ]; then
        wants_dir="${user_home}/.config/systemd/user/default.target.wants"
    fi
    for iface in slack mattermost matrix nextcloud; do
        enabled=0
        if $sysctl is-enabled "assistant-${iface}.service" 2>/dev/null | grep -q enabled; then
            enabled=1
        elif [ -n "$wants_dir" ] && [ -L "${wants_dir}/assistant-${iface}.service" ]; then
            enabled=1
        fi
        if [ "$enabled" = "1" ]; then
            interfaces="${interfaces:+${interfaces},}${iface}"
        fi
    done

    if [ -z "$interfaces" ]; then
        # No legacy units enabled. If the new unit is already enabled, restart
        # it on upgrade. Otherwise nothing to do.
        if $sysctl is-enabled assistant-orchestrator.service 2>/dev/null | grep -q enabled; then
            $sysctl daemon-reload 2>/dev/null || true
            $sysctl restart assistant-orchestrator.service 2>/dev/null || true
        fi
        return
    fi

    # Bail if we couldn't resolve the home directory (already attempted above).
    if [ -z "$user_home" ]; then
        return
    fi

    # Write the env file with the discovered interface list — only if the
    # operator hasn't already set ASSISTANT_INTERFACES themselves.
    env_dir="${user_home}/.config/assistant"
    env_file="${env_dir}/orchestrator.env"
    if [ ! -f "$env_file" ] || ! grep -q '^ASSISTANT_INTERFACES=' "$env_file" 2>/dev/null; then
        mkdir -p "$env_dir"
        chown "$user_id" "$env_dir" 2>/dev/null || true
        cat > "$env_file" <<INNER_EOF
# Auto-generated by package upgrade migration ($(date -u +%Y-%m-%dT%H:%M:%SZ)).
# Edit and restart with: systemctl --user restart assistant-orchestrator
ASSISTANT_INTERFACES=${interfaces}
INNER_EOF
        chown "$user_id" "$env_file" 2>/dev/null || true
        chmod 600 "$env_file" 2>/dev/null || true
    fi

    # Stop + disable the legacy units, then enable + start the new one.
    # `disable` is a no-op once the unit file is gone, so also remove any
    # dangling symlinks under default.target.wants/ that systemd would
    # otherwise keep complaining about as "not-found".
    for iface in slack mattermost matrix nextcloud; do
        $sysctl stop "assistant-${iface}.service" 2>/dev/null || true
        $sysctl disable "assistant-${iface}.service" 2>/dev/null || true
        if [ -n "$wants_dir" ] && [ -L "${wants_dir}/assistant-${iface}.service" ]; then
            rm -f "${wants_dir}/assistant-${iface}.service"
        fi
    done
    $sysctl reset-failed 2>/dev/null || true
    $sysctl daemon-reload 2>/dev/null || true
    $sysctl enable --now assistant-orchestrator.service 2>/dev/null || true
}

if [ "$action" = "configure" ] && [ -n "$2" ]; then
    # $2 is set to the old version on upgrade.
    #
    # loginctl list-sessions is unreliable in non-interactive dpkg contexts
    # (e.g. during a self-triggered apt upgrade). Instead, iterate over
    # /run/systemd/users/ which lists UIDs of all active user manager instances.
    for uid_path in /run/systemd/users/*; do
        user_id=$(basename "$uid_path")
        # Skip non-numeric entries.
        case "$user_id" in
            *[!0-9]*) continue ;;
        esac
        # Skip system users (UID < 1000).
        if [ "$user_id" -lt 1000 ] 2>/dev/null; then
            continue
        fi

        # 1. Migrate orchestrator if needed.
        migrate_user_to_orchestrator "$user_id"

        # 2. Restart web-ui if it was previously enabled.
        sysctl="systemctl --user -M ${user_id}@.host"
        if $sysctl is-enabled assistant-web-ui.service 2>/dev/null | grep -q enabled; then
            $sysctl daemon-reload 2>/dev/null || true
            $sysctl restart assistant-web-ui.service 2>/dev/null || true
        fi
    done
else
    cat <<'MSG'

assistant has been installed.

Two long-lived services are shipped:

  - assistant-orchestrator   (scheduler + bus + interface adapters)
  - assistant-web-ui         (HTTP API server)

Enable and start the ones you want:

  systemctl --user enable --now assistant-web-ui

  # Configure interfaces, then enable the orchestrator:
  mkdir -p ~/.config/assistant
  echo 'ASSISTANT_INTERFACES=slack,matrix' > ~/.config/assistant/orchestrator.env
  systemctl --user enable --now assistant-orchestrator

To have the services start at boot even when you are not logged in:

  loginctl enable-linger $USER

View logs with:

  journalctl --user -u assistant-orchestrator -f
  journalctl --user -u assistant-web-ui -f

MSG
fi
