import 'package:test/test.dart';
import 'package:assistant_api/assistant_api.dart';

// tests for Task
void main() {
  final instance = TaskBuilder();
  // TODO add properties to the builder and call build()

  group(Task, () {
    // Output artifacts for the task.
    // BuiltList<Artifact> artifacts
    test('to test the property `artifacts`', () async {
      // TODO
    });

    // Unique identifier (UUID) for the contextual collection of interactions.
    // String contextId
    test('to test the property `contextId`', () async {
      // TODO
    });

    // The history of interactions for this task.
    // BuiltList<Message> history
    test('to test the property `history`', () async {
      // TODO
    });

    // Unique identifier (UUID) for the task, generated by the server.
    // String id
    test('to test the property `id`', () async {
      // TODO
    });

    // Custom metadata about the task.
    // BuiltMap<String, JsonObject> metadata
    test('to test the property `metadata`', () async {
      // TODO
    });

    // The current status of the task.
    // TaskStatus status
    test('to test the property `status`', () async {
      // TODO
    });
  });
}
